apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cmxg5a1pt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cmxg5a1pt-java-quarkus-gitops